//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTriger
    {
        public short Code { get; set; }
        public int Value { get; set; }
        public short EmailFlag { get; set; }
        public int Value2 { get; set; }
        public Nullable<int> AlertId { get; set; }
    }
}
