//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.ClientAccounts = new HashSet<ClientAccount>();
        }
    
        public short CODE { get; set; }
        public string DSCR { get; set; }
        public string TotalUse { get; set; }
        public short FreePrint { get; set; }
        public string SecondDSCR { get; set; }
        public Nullable<short> TaxExempt { get; set; }
        public Nullable<int> TransferLimitFrom { get; set; }
        public Nullable<short> AllowCreditTransfer { get; set; }
        public Nullable<int> ExcludeFromBalance { get; set; }
        public Nullable<int> MinTransactionAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientAccount> ClientAccounts { get; set; }
    }
}
