//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int AlertID { get; set; }
        public short AlertLanguage { get; set; }
        public string AlertName { get; set; }
        public int AlertType { get; set; }
        public Nullable<int> AlertGroup { get; set; }
        public string DefaultAlertSubject { get; set; }
        public string AlertSubject { get; set; }
        public string AlertDefaultMessage { get; set; }
        public string AlertMessage { get; set; }
        public Nullable<int> AlertMinPeriodHours { get; set; }
    
        public virtual AlertGroup AlertGroup1 { get; set; }
        public virtual AlertType AlertType1 { get; set; }
    }
}
