//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveCommMessage
    {
        public int MessageID { get; set; }
        public string DefaultMessage { get; set; }
        public string CustomMessage { get; set; }
        public short MessageLineLenght { get; set; }
        public short UseCustom { get; set; }
        public short Language { get; set; }
        public string MsgGroup { get; set; }
        public string MsgType { get; set; }
        public string DSCR { get; set; }
        public int CODE { get; set; }
    }
}
