//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditID { get; set; }
        public System.DateTime AuditDateTime { get; set; }
        public string IPAddress { get; set; }
        public string AppName { get; set; }
        public string AppID { get; set; }
        public string OperatorId { get; set; }
        public string EventType { get; set; }
        public string ChangedTable { get; set; }
        public string ChangedField { get; set; }
        public string ChangedRecordID { get; set; }
        public string Value { get; set; }
    }
}
