//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceTransfer
    {
        public int BalanceTransferID { get; set; }
        public int FromAccountID { get; set; }
        public int ToAccountID { get; set; }
        public short TransferCode { get; set; }
        public Nullable<short> AllowCreditTransfer { get; set; }
    }
}
