//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardIssue
    {
        public string ID_NO { get; set; }
        public string TAG_NO { get; set; }
        public System.DateTime ISSUED_AT { get; set; }
        public System.DateTime RETURNED_AT { get; set; }
        public string COMMENT { get; set; }
    }
}
