//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccount
    {
        public string ClientID { get; set; }
        public short AccountId { get; set; }
        public int BALANCE { get; set; }
        public int CREDITLIMIT { get; set; }
        public short UNLIMITED { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Client Client { get; set; }
    }
}
