//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAlert
    {
        public string ClientID { get; set; }
        public int AlertID { get; set; }
        public string VarField1 { get; set; }
        public Nullable<System.DateTime> SentDT { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
