//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPlansUnlimited
    {
        public string ClientID { get; set; }
        public int PlanID { get; set; }
        public System.DateTime PlanStartDate { get; set; }
        public Nullable<System.DateTime> LastMealTime { get; set; }
        public Nullable<int> WeekMealCount { get; set; }
        public Nullable<int> WeekDayCount { get; set; }
        public Nullable<int> OrderIndex { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
