//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CngClientAccount
    {
        public string ID_NO { get; set; }
        public System.DateTime CNG_DATE { get; set; }
        public string LOGIN { get; set; }
        public short ACC_CODE { get; set; }
        public string LOG { get; set; }
    }
}
