//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class corTransDevice
    {
        public int DeviceID { get; set; }
        public System.DateTime TransDate { get; set; }
        public int TransNo { get; set; }
        public string ClientID { get; set; }
        public short TrnCode { get; set; }
        public System.DateTime PostingDate { get; set; }
        public string CardID { get; set; }
        public int Amount { get; set; }
        public string AccCode { get; set; }
        public byte IsOnline { get; set; }
        public int Tax1 { get; set; }
        public int Tax2 { get; set; }
        public int Tax3 { get; set; }
        public int Tax4 { get; set; }
        public int Tax1Removed { get; set; }
        public int Tax2Removed { get; set; }
        public int Tax3Removed { get; set; }
        public int Tax4Removed { get; set; }
    }
}
