//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpyDevicePaper
    {
        public int DeviceID { get; set; }
        public short PrLine1PaperID { get; set; }
        public short PrLine2PaperID { get; set; }
        public short PrLine3PaperID { get; set; }
        public short PrLine4PaperID { get; set; }
    }
}
