//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpyPaper
    {
        public short PaperID { get; set; }
        public string PaperName { get; set; }
        public int CopyPrice { get; set; }
        public short IsColor { get; set; }
        public short JobID { get; set; }
    }
}
