//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential
    {
        public string ClientID { get; set; }
        public int CredentialTypeID { get; set; }
        public string Auth1 { get; set; }
        public string Auth2 { get; set; }
        public Nullable<short> ManuelEntryAllowed { get; set; }
        public Nullable<short> Auth2Required { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<short> Reset { get; set; }
        public Nullable<short> Valid { get; set; }
        public Nullable<short> Locked { get; set; }
        public Nullable<int> LockoutAttempts { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<short> PrimaryCredential { get; set; }
    
        public virtual CredentialType CredentialType { get; set; }
    }
}
