//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CredentialType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CredentialType()
        {
            this.Credentials = new HashSet<Credential>();
        }
    
        public int CredentialTypeID { get; set; }
        public string CredentialName { get; set; }
        public string Description { get; set; }
        public Nullable<short> ManuelEntryAllowed { get; set; }
        public Nullable<short> Auth2Required { get; set; }
        public Nullable<short> Auth2Hashed { get; set; }
        public string Auth1Label { get; set; }
        public string Auth2Label { get; set; }
        public string Temp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credential> Credentials { get; set; }
    }
}
