//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceGroupProfile
    {
        public int DeviceGroupID { get; set; }
        public int ProfileID { get; set; }
        public short ChargeType { get; set; }
        public short Enabled { get; set; }
    }
}
