//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDMS_Link
    {
        public int ID { get; set; }
        public string ITCMultiplanFieldName { get; set; }
        public string IDMSFiledName { get; set; }
        public string Description { get; set; }
        public string DataType { get; set; }
        public string Size { get; set; }
    }
}
