//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public short CODE { get; set; }
        public string DSCR { get; set; }
        public short FromTime { get; set; }
        public short ToTime { get; set; }
        public string PlansPerDay { get; set; }
        public string sun { get; set; }
        public string mon { get; set; }
        public string tues { get; set; }
        public string wesd { get; set; }
        public string thur { get; set; }
        public string fri { get; set; }
        public string sat { get; set; }       
    }
}
