//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class New_ITC_WMMEntities : DbContext
    {
        public New_ITC_WMMEntities()
            : base("name=New_ITC_WMMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auditLog> auditLogs { get; set; }
        public virtual DbSet<deviceType> deviceTypes { get; set; }
        public virtual DbSet<loginLog> loginLogs { get; set; }
        public virtual DbSet<permissionsAssigned> permissionsAssigneds { get; set; }
        public virtual DbSet<permissionsGrant> permissionsGrants { get; set; }
        public virtual DbSet<permissionsRolesTask> permissionsRolesTasks { get; set; }
        public virtual DbSet<permissionsTask> permissionsTasks { get; set; }
        public virtual DbSet<pref> prefs { get; set; }
        public virtual DbSet<reportLog> reportLogs { get; set; }
        public virtual DbSet<reportrun> reportruns { get; set; }
        public virtual DbSet<reportschedule> reportschedules { get; set; }
        public virtual DbSet<reportsStored> reportsStoreds { get; set; }
        public virtual DbSet<reportsStored_preview> reportsStored_preview { get; set; }
        public virtual DbSet<theme> themes { get; set; }
        public virtual DbSet<timezone> timezones { get; set; }
        public virtual DbSet<translation> translations { get; set; }
        public virtual DbSet<translationsource> translationsources { get; set; }
        public virtual DbSet<AllLanguage> AllLanguages { get; set; }
        public virtual DbSet<ThemeSetting> ThemeSettings { get; set; }
        public virtual DbSet<TblFont> TblFonts { get; set; }
    }
}
