//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class New_ITC_MultiplanEntities : DbContext
    {
        public New_ITC_MultiplanEntities()
            : base("name=New_ITC_MultiplanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountCode> AccountCodes { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccProfileWebDeposit> AccProfileWebDeposits { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<BalanceTransfer> BalanceTransfers { get; set; }
        public virtual DbSet<BeanStreamSession> BeanStreamSessions { get; set; }
        public virtual DbSet<ClientAccountCode> ClientAccountCodes { get; set; }
        public virtual DbSet<ClientAccount> ClientAccounts { get; set; }
        public virtual DbSet<ClientPlan> ClientPlans { get; set; }
        public virtual DbSet<ClientPlansUnlimited> ClientPlansUnlimiteds { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<corClientPicture> corClientPictures { get; set; }
        public virtual DbSet<corTransDevice> corTransDevices { get; set; }
        public virtual DbSet<CostCentre> CostCentres { get; set; }
        public virtual DbSet<cpyDevicePaper> cpyDevicePapers { get; set; }
        public virtual DbSet<cpyPaper> cpyPapers { get; set; }
        public virtual DbSet<cpyTransaction> cpyTransactions { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<CredentialType> CredentialTypes { get; set; }
        public virtual DbSet<CustomField> CustomFields { get; set; }
        public virtual DbSet<CustomUserData> CustomUserDatas { get; set; }
        public virtual DbSet<DailyLimit> DailyLimits { get; set; }
        public virtual DbSet<DelClient> DelClients { get; set; }
        public virtual DbSet<DeviceGroupProfile> DeviceGroupProfiles { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<Param> Params { get; set; }
        public virtual DbSet<ParamsExport> ParamsExports { get; set; }
        public virtual DbSet<ParkingGroup> ParkingGroups { get; set; }
        public virtual DbSet<ParkingPrice> ParkingPrices { get; set; }
        public virtual DbSet<PayMethod> PayMethods { get; set; }
        public virtual DbSet<PlanLimit> PlanLimits { get; set; }
        public virtual DbSet<PlanProfileWebDeposit> PlanProfileWebDeposits { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Port> Ports { get; set; }
        public virtual DbSet<ProfileDepositLimit> ProfileDepositLimits { get; set; }
        public virtual DbSet<prtMachine> prtMachines { get; set; }
        public virtual DbSet<prtPrinter> prtPrinters { get; set; }
        public virtual DbSet<prtPrinterGroup> prtPrinterGroups { get; set; }
        public virtual DbSet<prtTransaction> prtTransactions { get; set; }
        public virtual DbSet<RegisterGroupPlanLimit> RegisterGroupPlanLimits { get; set; }
        public virtual DbSet<RegisterGroup> RegisterGroups { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<RightGroup> RightGroups { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblEvent> tblEvents { get; set; }
        public virtual DbSet<TMP_Profiles> TMP_Profiles { get; set; }
        public virtual DbSet<TrnDep> TrnDeps { get; set; }
        public virtual DbSet<TrnPayrol> TrnPayrols { get; set; }
        public virtual DbSet<TrnPlan> TrnPlans { get; set; }
        public virtual DbSet<TrnReg> TrnRegs { get; set; }
        public virtual DbSet<TrnRegNoClient> TrnRegNoClients { get; set; }
        public virtual DbSet<vndItem> vndItems { get; set; }
        public virtual DbSet<vndMachineItem> vndMachineItems { get; set; }
        public virtual DbSet<vndTransaction> vndTransactions { get; set; }
        public virtual DbSet<AccountTriger> AccountTrigers { get; set; }
        public virtual DbSet<CardIssue> CardIssues { get; set; }
        public virtual DbSet<CngClientAccount> CngClientAccounts { get; set; }
        public virtual DbSet<IDMS_Link> IDMS_Link { get; set; }
        public virtual DbSet<JobType> JobTypes { get; set; }
        public virtual DbSet<ParkingCalendar> ParkingCalendars { get; set; }
        public virtual DbSet<SiteKey> SiteKeys { get; set; }
        public virtual DbSet<AlertGroup> AlertGroups { get; set; }
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<AlertType> AlertTypes { get; set; }
        public virtual DbSet<CreditCardProcessSession> CreditCardProcessSessions { get; set; }
        public virtual DbSet<FieldPicker> FieldPickers { get; set; }
        public virtual DbSet<ClientAlert> ClientAlerts { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<CommMessage> CommMessages { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<ArchiveCommMessage> ArchiveCommMessages { get; set; }
    }
}
