//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        //public string LOGIN { get; set; }
        public string FAMILY { get; set; }
        public string GIVEN { get; set; }
        //public string PASSWORD { get; set; }
        public short RightGroup { get; set; }
        public string COMMENT { get; set; }
        public string DevGroup { get; set; }
        public string Profile { get; set; }
        public string Account { get; set; }
        public Nullable<short> DP { get; set; }
        public string Email { get; set; }
    }
}
