//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingPrice
    {
        public int ID { get; set; }
        public Nullable<int> Profile { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<short> Day_Evening { get; set; }
    }
}
