//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingGroup
    {
        public int GroupNumber { get; set; }
        public string ParkingPermit { get; set; }
        public Nullable<short> DayEvening { get; set; }
        public Nullable<short> Custom { get; set; }
        public string DSCR { get; set; }
    }
}
