//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingCalendar
    {
        public int ID { get; set; }
        public short Type { get; set; }
        public Nullable<System.DateTime> OffDate { get; set; }
        public Nullable<short> Every { get; set; }
        public Nullable<short> DayOfWeek { get; set; }
        public string DayOfWeekName { get; set; }
        public Nullable<short> WeekOfMonth { get; set; }
        public string WeekOfMonthName { get; set; }
        public Nullable<short> DayOfMonth { get; set; }
        public Nullable<short> OfMonth { get; set; }
        public string OfMonthName { get; set; }
        public string EveryName { get; set; }
    }
}
