//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.ClientPlansUnlimiteds = new HashSet<ClientPlansUnlimited>();
        }
    
        public int CODE { get; set; }
        public string DSCR { get; set; }
        public string REGS { get; set; }
        public string MEALS { get; set; }
        public short IS_DAYS { get; set; }
        public short DAYS { get; set; }
        public System.DateTime START_DATE { get; set; }
        public short IS_EXPIRY_DATE { get; set; }
        public System.DateTime EXPIRY_DATE { get; set; }
        public short IsTotalMealsPerPlan { get; set; }
        public short TotalMealsPerPlan { get; set; }
        public int IsTotalAmountPerPlan { get; set; }
        public int TotalAmountPerPlan { get; set; }
        public short IsTotalMealsPerWeek { get; set; }
        public short TotalMealsPerWeek { get; set; }
        public short EnableMultipleMeals { get; set; }
        public int PRICE { get; set; }
        public short PrintMode { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public short AccountID { get; set; }
        public int Bonus { get; set; }
        public short PassBack { get; set; }
        public short AuthorizationRequired { get; set; }
        public short DaysPerWeek { get; set; }
        public string SecondDSCR { get; set; }
        public Nullable<short> AllowParking { get; set; }
        public Nullable<int> ParkGroup { get; set; }
        public Nullable<short> TaxExempt { get; set; }
        public Nullable<int> BonusPlanCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlansUnlimited> ClientPlansUnlimiteds { get; set; }
    }
}
