//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanLimit
    {
        public int PlanCode { get; set; }
        public short MealCode { get; set; }
        public short IsMealsPerPlan { get; set; }
        public short MealsPerPlan { get; set; }
        public short IsAmountPerPlan { get; set; }
        public int AmountPerPlan { get; set; }
        public short IsAmountPerMeal { get; set; }
        public int AmountPerMeal { get; set; }
        public short IsMealsPerDay { get; set; }
        public int MealsPerDay { get; set; }
        public Nullable<short> IsMinAmountPerMeal { get; set; }
        public Nullable<int> MinAmountPerMeal { get; set; }
        public string MealDescription { get; internal set; }
    }
}
