//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Port
    {
        public short Desktop { get; set; }
        public int PortNo { get; set; }
        public string Description { get; set; }
        public int BaudRate { get; set; }
        public int DataBits { get; set; }
        public int StopBits { get; set; }
        public string Parity { get; set; }
        public short Mode { get; set; }
        public int GoOfflineAfter { get; set; }
        public int LoadOldRecordsEvery { get; set; }
        public short Enabled { get; set; }
        public string ActiveTimeMap { get; set; }
        public short ModemEnabled { get; set; }
        public string ModemInitString { get; set; }
        public short ModemPulse { get; set; }
        public int ModemAnswerDelay { get; set; }
        public int ModemDialRetries { get; set; }
    }
}
