//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileDepositLimit
    {
        public short ProfileCode { get; set; }
        public short AccCode { get; set; }
        public int MaxLimit { get; set; }
        public short Period { get; set; }
        public int PeriodLimit { get; set; }
        public int PeriodCount { get; set; }
    }
}
