//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prtPrinter
    {
        public int PrinterID { get; set; }
        public string PrinterName { get; set; }
        public int PrinterGroupID { get; set; }
        public int DeviceID { get; set; }
    }
}
