//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prtTransaction
    {
        public int DeviceID { get; set; }
        public System.DateTime TransDate { get; set; }
        public int TransNo { get; set; }
        public string ClientID { get; set; }
        public int MachineID { get; set; }
        public int PrinterID { get; set; }
        public int PageCount { get; set; }
    }
}
