//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int CODE { get; set; }
        public string DSCR { get; set; }
        public short Enabled { get; set; }
        public string IPAddress { get; set; }
        public string ACCOUNTS { get; set; }
        public string LoadOldTimeMap { get; set; }
        public string OffFileTimeMap { get; set; }
        public short OffFileNegativeEnabled { get; set; }
        public int OffFileMaxNumber { get; set; }
        public short ModemEnabled { get; set; }
        public string ModemPhoneNumber { get; set; }
        public int RegisterType { get; set; }
        public short GROUP_CODE { get; set; }
        public short Desktop { get; set; }
        public int ERA570OfflineMax { get; set; }
        public string Budget { get; set; }
        public string AccountDiscounts { get; set; }
        public short UseExtendedPassBack { get; set; }
        public short ExtendedPassBack { get; set; }
        public System.DateTime LastConnectionTime { get; set; }
        public string MACAddress { get; set; }
        public short Initializetype { get; set; }
        public short ExtendedPassBackReset { get; set; }
        public Nullable<System.DateTime> NewCardsLastSyncTime { get; set; }
        public Nullable<System.DateTime> DeletedCardsLastSyncTime { get; set; }
        public Nullable<short> PrimaryCredentialOnly { get; set; }
        public Nullable<short> CreateVirtualPlan { get; set; }
    }
}
