//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportrun
    {
        public int id { get; set; }
        public string reportRunName { get; set; }
        public string reportid { get; set; }
        public int scheduleid { get; set; }
        public Nullable<System.DateTime> nextRun { get; set; }
        public Nullable<System.DateTime> firstRun { get; set; }
        public Nullable<System.DateTime> lastRun { get; set; }
        public string deliverTo { get; set; }
        public string deliverSubject { get; set; }
        public string fileType { get; set; }
        public int status { get; set; }
    }
}
