//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        public int ID { get; set; }
        public int REG_CODE { get; set; }
        public string EVENT_TYPE { get; set; }
        public System.DateTime TRNDATE { get; set; }
        public string ACTION { get; set; }
    }
}
