//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class ThemeSetting
    {
        public int ThemeSettingId { get; set; }
        public int ThemeId { get; set; }
        public string ThemeSettingName { get; set; }
        public string ThemeSettingValue { get; set; }
        public string Placeholder { get; set; }
    
        public virtual theme theme { get; set; }
    }
}
