//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_Profiles
    {
        public short CODE { get; set; }
        public string DSCR { get; set; }
        public int DiscountPercent { get; set; }
        public short ResetBalanceEnabled { get; set; }
        public int ResetBalanceValue { get; set; }
        public short ResetFrequency { get; set; }
        public short ResetDayOfWeek { get; set; }
        public short ResetDayOfMonth { get; set; }
        public short ResetBalanceFrom { get; set; }
        public short ResetBalanceTo { get; set; }
        public System.DateTime ResetBalanceLast { get; set; }
        public short IsCashOnly { get; set; }
        public short RemoveTax1 { get; set; }
        public short RemoveTax2 { get; set; }
        public short RemoveTax3 { get; set; }
        public short RemoveTax4 { get; set; }
        public short RemoveTax5 { get; set; }
        public short ProCompleteNonTaxableAccount { get; set; }
        public short AccCode { get; set; }
        public string SecondDSCR { get; set; }
    }
}
