//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class translation
    {
        public int id { get; set; }
        public int sourceid { get; set; }
        public string language { get; set; }
        public string translation1 { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modifier { get; set; }
    
        public virtual translationsource translationsource { get; set; }
    }
}
