//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrnReg
    {
        public int REG_CODE { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public int TRN_NO { get; set; }
        public short TrnCode { get; set; }
        public short ACC_CODE { get; set; }
        public string ID_NO { get; set; }
        public int AMOUNT { get; set; }
        public string TAG_NO { get; set; }
        public short Desktop { get; set; }
        public int PLAN_CODE { get; set; }
        public System.DateTime TRN_DATE { get; set; }
        public int BALANCE { get; set; }
        public short ON_LINE { get; set; }
        public short MEAL_CODE { get; set; }
        public string AccCode { get; set; }
        public short ApplicationId { get; set; }
        public int DISCOUNT { get; set; }
        public short PaymentId { get; set; }
        public string Comment { get; set; }
        public Nullable<short> CreditCardType { get; set; }
        public Nullable<int> CreditCardAuthNumber { get; set; }
    }
}
