//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITC_Matrix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vndTransaction
    {
        public int DeviceID { get; set; }
        public System.DateTime TransDate { get; set; }
        public int TransNo { get; set; }
        public int HardwareCode { get; set; }
        public int ItemID { get; set; }
    }
}
